# Generated by Django 4.2.18 on 2025-01-29 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_amortizationschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='term_months',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
