# Generated by Django 4.2.18 on 2025-01-29 23:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_bankloantype_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amortizationschedule',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='bank_loan_type',
        ),
        migrations.DeleteModel(
            name='LoanType',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bank',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='AmortizationSchedule',
        ),
        migrations.DeleteModel(
            name='BankLoanType',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
